# Generated by Django 2.1 on 2018-08-07 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordwiki', '0002_auto_20180807_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Keyword description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Resource summary'),
        ),
    ]
